export const highlightEvents = [
  {
    title: "Mr. and Ms. Saavyas",
    fileName: "m-rs-saavyas.jpeg",
    link: "/events/cultural/#m-rs-saavyas",
  },
  {
    title: "Shake it UP",
    fileName: "solo-dance.jpeg",
    link: "/events/cultural/#solo-dance",
  },
]

export const events = [
  {
    id: "m-rs-saavyas",
    titleA: "Mr. and Ms.",
    titleB: "Saavyas",
    eventDate: "8th and 9th March",
    // eventTime: "11:00 AM",
    eventZone: "Echo",
    eventPrize: "Rs 8k",
    eventFee: 100,
    // eventLocation: "Ground Sector 1",
    imageFileName: "m-rs-saavyas.jpeg",
    coordinators: [
      {
        name: "Srishti Patkar",
        phoneNo: "7038316173",
      },
      {
        name: "Alisha Thorat",
        phoneNo: "7507763915",
      },
    ],
    eventSummary:
      "Personality hunt competition. Long ago, tribes used daring feats of skill and bravery to choose the worthiest amongst them. The stage sets on fire, when the unseen, unforgettable, ultimate accessory and perception of fashion heralds the arrival of blistering and dynamic youth of this country which finally leads to a classic style of a competition.",
  },
  {
    id: "solo-singing",
    titleA: "The Voice",
    titleB: "Solo Singing",
    eventDate: "8th March",
    // eventTime: "10:00 AM",
    eventZone: "Bravo",
    // eventLocation: "Seminar Hall",
    eventFee: 50,
    eventPrize: "Rs 2k",
    imageFileName: "solo-singing.jpeg",
    coordinators: [
      {
        name: "Priyancy Gautam",
        phoneNo: "9359173162",
      },
      {
        name: "Amit",
        phoneNo: "6377738495",
      },
    ],
    eventSummary: "",
  },
  {
    id: "duet-singing",
    titleA: "Duetto Chanter",
    titleB: "Duet Singing",
    eventDate: "8th March",
    // eventTime: "12:00 PM",
    eventZone: "Bravo",
    // eventLocation: "Seminar Hall",
    eventFee: 100,
    eventPrize: "Rs 3k",
    imageFileName: "duet-singing.jpeg",
    coordinators: [
      {
        name: "Durva Valvaikar",
        phoneNo: "9552714122",
      },
    ],
    eventSummary: "",
  },
  {
    id: "solo-dance",
    titleA: "Shake it UP",
    titleB: "Solo Street Dance",
    eventDate: "8th March",
    // eventTime: "10:00 AM",
    eventZone: "Echo",
    // eventLocation: "Ground Sector 1",
    eventFee: 100,
    eventPrize: "Rs 7k",
    imageFileName: "solo-dance.jpeg",
    coordinators: [
      {
        name: "Arjun",
        phoneNo: "7798707363",
      },
      {
        name: "Samruddhi",
        phoneNo: "9146384057",
      },
    ],
    eventSummary: "",
  },
  {
    id: "group-dance",
    titleA: "Sizzle",
    titleB: "Group Dance",
    eventDate: "9th March",
    // eventTime: "4:00 PM",
    eventZone: "Echo",
    // eventLocation: "Ground Sector 1",
    eventPrize: "Rs 10k",
    eventFee: 500,
    imageFileName: "group-dance.jpeg",
    coordinators: [
      {
        name: "Karun Raj",
        phoneNo: "8639148574",
      },
      {
        name: "Poreddy Maniteja",
        phoneNo: "8886321272",
      },
    ],
    eventSummary: "",
  },
  {
    id: "treasure-hunt",
    titleA: "The Night Kings Treasure",
    titleB: "Treasure Hunt",
    eventDate: "9th March",
    // eventTime: "11:00 AM",
    eventZone: "Campus",
    // eventLocation: "Campus",
    eventFee: 100,
    eventPrize: "Rs 3k",
    imageFileName: "treasure-hunt.jpeg",
    coordinators: [
      {
        name: "Gaurav Naik",
        phoneNo: "9359095548",
      },
      {
        name: "Mayank Ashtikar",
        phoneNo: "9420644232",
      },
    ],
    eventSummary: `Follow a series of clue or clues,
      Be clever and skillful and don't be blue.`,
  },
  {
    id: "face-paint",
    titleA: "Frosty Face",
    titleB: "Face Paint",
    eventDate: "9th March",
    // eventTime: "1:00 PM",
    eventZone: "Bravo",
    // eventLocation: "N5",
    eventPrize: "Rs 1.5k",
    eventFee: 50,
    imageFileName: "face-paint.jpeg",
    coordinators: [
      {
        name: "Sanjana Naik",
        phoneNo: "7066129868",
      },
      {
        name: "B Guna",
        phoneNo: "8330988069",
      },
    ],
    eventSummary: "",
  },
  {
    id: "third-degree",
    titleA: "Trials by Fire",
    titleB: "3rd Degree",
    eventDate: "8th and 9th March",
    // eventTime: "11:00 AM",
    eventZone: "Golf",
    // eventLocation: "Parking Lot",
    eventFee: 100,
    eventPrize: "Rs 3k",
    imageFileName: "third-degree.jpeg",
    coordinators: [
      {
        name: "Vinish Thanai",
        phoneNo: "8094932667",
      },
      {
        name: "Ritesh Yadav",
        phoneNo: "9067826501",
      },
    ],
    eventSummary:
      "Fight the bulls by the horns. An euphemism for torture, prepare yourself for TRIALS OF FIRE.",
  },
  {
    id: "mono-act",
    titleA: "Meltdown",
    titleB: "Mono Act",
    eventDate: "8th March",
    // eventTime: "12:00 PM",
    eventZone: "Echo",
    // eventLocation: "Ground Sector 1",
    eventFee: 50,
    eventPrize: "Rs 2k",
    imageFileName: "mono-act.jpeg",
    coordinators: [
      {
        name: "Divyani",
        phoneNo: "9502542067",
      },
    ],
    eventSummary: "",
  },
  {
    id: "rangoli",
    titleA: "Color Blaze",
    titleB: "Rangoli",
    eventDate: "9th March",
    // eventTime: "10:00 AM",
    eventZone: "Bravo",
    // eventLocation: "N8",
    eventFee: 50,
    eventPrize: "Rs 1.5k",
    imageFileName: "rangoli.jpeg",
    coordinators: [
      {
        name: "Sanjana Naik",
        phoneNo: "7066129868",
      },
      {
        name: "B Guna",
        phoneNo: "8330988069",
      },
    ],
    eventSummary: `Show your skills with Rangoli powder on the floor,
    Fail to succeed, and there's the door.`,
  },
  {
    id: "suprise-event",
    titleA: "Chill Thrills",
    titleB: "Surprise Event",
    eventDate: "8th and 9th March",
    // eventTime: "2:00 PM",
    eventZone: "Echo",
    // eventLocation: "Ground Sector 1",
    eventFee: 100,
    eventPrize: "Rs 2k",
    imageFileName: "suprise-event.jpeg",
    coordinators: [
      {
        name: "Mayank Solanki",
        phoneNo: "9579934427",
      },
      {
        name: "Shivatman Pal",
        phoneNo: "8275857201",
      },
    ],
    eventSummary:
      "Introducing CHILL THRILLS. When we experience a surprise, when we have a set of expectations and we get something else, our brain doesn't really know what to do with it -- as opposed to looking forward to the future plans or looking to the past memories, like what am I doing this weekend? Come over to our campus during SAAVYAS to experience the unexpected.",
  },
  {
    id: "standup-comedy",
    titleA: "O'laf",
    titleB: "Standup Comedy",
    eventDate: "9th March",
    // eventTime: "2:00 PM",
    eventZone: "Echo",
    // eventLocation: "Ground Sector 1",
    eventFee: 100,
    eventPrize: "Rs 2k",
    imageFileName: "olaf.jpeg",
    coordinators: [
      {
        name: "Rosemary Santhosh",
        phoneNo: "8208165872",
      },
      {
        name: "Rosemary Santhosh",
        phoneNo: "9207602425",
      },
    ],
    eventSummary: `Get your best your jokes, don't u forget,
    The stage is yours,
    Let's see how many Olafs u get.`,
  },
]
