export const highlightEvents = []

export const events = [
  {
    id: "m-rs-saavyas",
    titleA: "Mr. and Ms.",
    titleB: "Saavyas",
    eventDate: "8th March",
    eventTime: "11:00 AM",
    eventZone: "Echo",
    eventLocation: "Ground Sector 1",
    eventSummary:
      "Personality hunt competition. Long ago, tribes used daring feats of skill and bravery to choose the worthiest amongst them. The stage sets on fire, when the unseen, unforgettable, ultimate accessory and perception of fashion heralds the arrival of blistering and dynamic youth of this country which finally leads to a classic style of a competition.",
  },
  {
    id: "solo-singing",
    titleA: "The Voice",
    titleB: "Solo Singing",
    eventDate: "8th March",
    eventTime: "10:00 AM",
    eventZone: "Bravo",
    eventLocation: "Seminar Hall",
    eventSummary: "",
  },
  {
    id: "duet-singing",
    titleA: "Duetto Chamber",
    titleB: "Solo Singing",
    eventDate: "8th March",
    eventTime: "12:00 PM",
    eventZone: "Bravo",
    eventLocation: "Seminar Hall",
    eventSummary: "",
  },
  {
    id: "solo-dance",
    titleA: "Shake it UP",
    titleB: "Solo Dance",
    eventDate: "8th March",
    eventTime: "10:00 AM",
    eventZone: "Echo",
    eventLocation: "Ground Sector 1",
    eventSummary: "",
  },
  {
    id: "duet-dance",
    titleA: "Flick a Move",
    titleB: "Duet Dance",
    eventDate: "8th March",
    eventTime: "12:00 PM",
    eventZone: "Echo",
    eventLocation: "Ground Sector 1",
    eventSummary: "",
  },
  {
    id: "group-dance",
    titleA: "Sizzle",
    titleB: "Group Dance",
    eventDate: "8th March",
    eventTime: "4:00 PM",
    eventZone: "Echo",
    eventLocation: "Ground Sector 1",
    eventSummary: "",
  },
  {
    id: "treasure-hunt",
    titleA: "The Night Kings Treasure",
    titleB: "Treasure Hunt",
    eventDate: "9th March",
    eventTime: "11:00 AM",
    eventZone: "Campus",
    eventLocation: "Campus",
    eventSummary: `Follow a series of clue or clues,
      Be clever and skillful and don't be blue.`,
  },
  {
    id: "face-paint",
    titleA: "Burning Bright",
    titleB: "Face Paint",
    eventDate: "9th March",
    eventTime: "1:00 PM",
    eventZone: "Bravo",
    eventLocation: "N5",
    eventSummary: "",
  },
  {
    id: "mime",
    titleA: "Frosty Face",
    titleB: "Mime",
    eventDate: "9th March",
    eventTime: "10:00 AM",
    eventZone: "Echo",
    eventLocation: "Ground Sector 1",
    eventSummary: `Show us a story, with your limbs and face,
    Shhhh don't talk, else you'll be replaced.`,
  },
  {
    id: "third-degree",
    titleA: "Trials by Fire",
    titleB: "3rd Degree",
    eventDate: "9th March",
    eventTime: "11:00 AM",
    eventZone: "Golf",
    eventLocation: "Parking Lot",
    eventSummary:
      "Fight the bulls by the horns. An euphemism for torture, prepare yourself for TRIALS OF FIRE.",
  },
  {
    id: "mono-act",
    titleA: "Meltdown",
    titleB: "Mono Act",
    eventDate: "9th March",
    eventTime: "12:00 PM",
    eventZone: "Echo",
    eventLocation: "Ground Sector 1",
    eventSummary: "",
  },
  {
    id: "rangoli",
    titleA: "Color Blaze",
    titleB: "Rangoli",
    eventDate: "9th March",
    eventTime: "10:00 AM",
    eventZone: "Bravo",
    eventLocation: "N8",
    eventSummary: `Show your skills with Rangoli powder on the floor,
    Fail to succeed, and there's the door.`,
  },
  {
    id: "suprise-event",
    titleA: "Chill Thrills",
    titleB: "Surprise Event",
    eventDate: "8th March",
    eventTime: "2:00 PM",
    eventZone: "Echo",
    eventLocation: "Ground Sector 1",
    eventSummary:
      "Introducing CHILL THRILLS. When we experience a surprise, when we have a set of expectations and we get something else, our brain doesn't really know what to do with it -- as opposed to looking forward to the future plans or looking to the past memories, like what am I doing this weekend? Come over to our campus during SAAVYAS to experience the unexpected.",
  },
  {
    id: "standup-comedy",
    titleA: "O'laf",
    titleB: "Standup Comedy",
    eventDate: "9th March",
    eventTime: "2:00 PM",
    eventZone: "Echo",
    eventLocation: "Ground Sector 1",
    eventSummary: `Get your best your jokes, don't u forget,
    The stage is yours,
    Let's see how many Olafs u get.`,
  },
]
