export const highlightEvents = []

export const events = [
  {
    id: "binge-eating",
    titleA: "Icy Spicy",
    titleB: "Binge Eating",
    eventDate: "9th March",
    eventTime: "2:00 PM",
    eventZone: "Charlie",
    eventLocation: "Library Lawn",
    eventPrize: "Rs 1.5k",
    eventSummary: "",
  },
  {
    id: "ipl-auction",
    titleA: "IPL Auction",
    titleB: "IPL Auction",
    eventDate: "9th March",
    eventTime: "2:30 PM",
    eventZone: "Bravo",
    eventLocation: "Seminar Hall",
    eventPrize: "Rs 2k",
    eventSummary: "",
  },
  {
    id: "bazinga",
    titleA: "The Ice Storm",
    titleB: "Bazinga",
    eventDate: "8th March",
    eventTime: "2:00 PM",
    eventZone: "Bravo",
    eventLocation: "Seminar Hall",
    eventPrize: "Rs 3k",
    eventSummary: "",
  },
  {
    id: "trivium",
    titleA: "Rapid Fire",
    titleB: "Trivium",
    eventDate: "9th March",
    eventTime: "10:00 AM",
    eventZone: "Bravo",
    eventLocation: "Seminar Hall",
    eventPrize: "Rs 3k",
    eventSummary: "",
  },
  {
    id: "min-to-win",
    titleA: "Feel the Heat",
    titleB: "Minute to win it",
    eventDate: "9th March",
    eventTime: "1:30 PM",
    eventZone: "Bravo",
    eventLocation: "Seminar Hall",
    eventPrize: "Rs 2k",
  },
]
