export const highlightEvents = []

export const events = [
  {
    id: "chess",
    titleA: "Brain Freeze",
    titleB: "Chess",
    eventDate: "7th March",
    eventTime: "10:30 AM",
    eventZone: "Alpha",
    eventLocation: "N2/N4",
    eventPrize: "Rs 11k",
    eventSummary: "",
  },
  {
    id: "table-tennis",
    titleA: "Hot Shots",
    titleB: "Table Tennis",
    eventDate: "7th March",
    eventTime: "10:30 AM",
    eventZone: "Bravo",
    eventLocation: "N5/N6",
    eventPrize: "Rs 7.5k",
    eventSummary: "",
  },
  {
    id: "football",
    titleA: "Futsal",
    titleB: "Football",
    eventDate: "7th and 8th March",
    eventTime: "10:30 AM",
    eventZone: "Echo",
    eventLocation: "Ground Sector 2",
    eventPrize: "Rs 24k",
    eventSummary: "",
  },
  {
    id: "pro-cricket",
    titleA: "Fireball",
    titleB: "Pro Cricket",
    eventDate: "8th March",
    eventTime: "12:00 PM",
    eventZone: "Echo",
    eventLocation: "Ground Sector 2",
    eventPrize: "Rs 6k",
    eventSummary: "",
  },
  {
    id: "pubg",
    titleA: "PUBG",
    eventDate: "8th March",
    eventTime: "2:00 PM",
    eventZone: "Bravo",
    eventLocation: "N8",
    eventPrize: "Rs 5k",
    eventSummary: "",
  },
  {
    id: "fifa",
    titleA: "FIFA",
    eventDate: "7th March",
    eventTime: "10:30 AM",
    eventZone: "Delta",
    eventLocation: "2A/2B",
    eventPrize: "Rs 5.5k",
    eventSummary: "",
  },
]
